# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
  input:          GFM

# Permalinks
permalink:        pretty

# Setup
title:            'UC Merced - <br> Spring 2023'
description:      'Data Science Research Biology: An intro to programming with R for ecology and evolution'
url:              http://www.datacarpentry.org/semester-biology
baseurl:          /spring2023-data-science
email:            sanchez.reyes.luna@gmail.com
feedbackurl:      docs.google.com/forms/d/1y35uJukuZ9MPKQWWqw0Y8R4VOiaOtFJezDY_t_kJfTs/
author:
  name:           'Luna Luisa Sanchez Reyes and Emily Jane McTavish'
  url:            https://mctavishlab.github.io/

github:
  repo:           https://github.com/LunaSare/spring2023-data-science.git
  #               Be sure the 'Issues' feature is activated in 'Settings'
